site_name: Mafia Wiki
site_url: https://mafiawiki.astrofare.xyz/
#repo_url: https://github.com/octanebula/mafiawiki
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: magenta
nav:
  - Home: index.md
extra:
  generator: false
  assets_dir: docs
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: false
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_css:
 - stylesheets/extra.css

