site_name: Mafia Wiki
site_url: https://mafiawiki.astrofare.xyz/
site_description: The official community-driven wiki for the Roblox game Mafia by Topline Studios.
#repo_url: https://github.com/octanebula/mafiawiki

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: magenta
  features:
    - navigation.instant.preview
    - navigation.indexes


nav:
  - Home: index.md
  - Roles: roles/index.md
  - Maps: maps/index.md
  - Perks: perks/index.md
  - Disguises: disguises/index.md
  - Lore: lore/index.md
  - Meta:
    - meta/index.md
    - Writing Guide: meta/writing-guide.md
    - Article Template: meta/article-template.md
    - Markdown Showcase: meta/markdown-formatting-showcase.md
    - Contributors: meta/contributors.md

extra:
  generator: false
  assets_dir: docs

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: false
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - md_in_html

extra_css:
  - stylesheets/extra.css

plugins:
  - search

hooks:
  - hooks/category_index.py