site_name: Official Mafia Wiki
site_url: https://mafiawiki.astrofare.xyz/
repo_url: https://github.com/octanebula/mafiawiki
theme:
  name: material
nav:
  - Home: index.md
extra:
  generator: false
extra_css:
  - stylesheets/extra.css